linters:
    enable:
        - dupl
        - forbidigo
        - goconst
        - gofmt
        - revive
        - typecheck
        - unparam
linters-settings:
    forbidigo:
        forbid:
        # https://go.dev/doc/go1.16#ioutil
        - ^ioutil\..*
