version: 2.1
executors:
  golang:
    docker:
      - image: quay.io/cybozu/golang:1.17-focal
jobs:
  lint:
    executor: golang
    steps:
      - checkout
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
          golangci-lint run --new-from-rev=HEAD~
  test:
    executor: golang
    steps:
      - checkout
      - run: make test
  build:
    executor: golang
    steps:
      - checkout
      - run: make build

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test
      - build
