version: 2.1
executors:
  golang:
    docker:
      - image: quay.io/cybozu/golang:1.15-focal
jobs:
  lint:
    executor: golang
    steps:
      - checkout
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
          golangci-lint run --new-from-rev=HEAD~
      - run: test -z "$(gofmt -s -l . | grep -v '^vendor' | tee /dev/stderr)"
      - run: golint -set_exit_status .
  test:
    executor: golang
    steps:
      - checkout
      - run: go test -race -v ./...
      - run: go vet ./...
  build:
    executor: golang
    steps:
      - checkout
      - run: go build ./...

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test
      - build
